### ISSUE TITLE
Dedicated Mode?

### ISSUE THREAD

**Issue by matt22207** [chikobara/GPU-Switcher-Supergfxctl#1]
Thanks for this one! 

Why is Dedicated GPU mode disabled?

https://github.com/chikobara/GPU-Switcher-Supergfxctl/blob/main/extension.js#L24

Thanks again!

**Comment by chikobara** [comment]
oh am sorry for that but i thought i won't use so i disabled it , 
ill update the extension soon so that dGPU mode will be available

**Comment by matt22207** [comment]
Awesome, thanks! 

I don't use dGPU mode too often, but if I want to sneak a few extra FPS, I can sometimes get another 5-10% (although I haven't tested the difference in a while)..

**Comment by chikobara** [comment]
> (although I haven't tested the difference in a while)..

actually thats true , 
but i still want to implement other modes cause there are more like ( Integrated Hybrid supergfxctl VFIO supergfxctl AsusEgpu AsusMuxDgpu ) 
so the extension can change to any mode if it was supported by the host

i got final exams these days so ill continue later <3

**Comment by chikobara** [comment]
> Why is Dedicated GPU mode disabled?

Hey there 
can you try doing `supergfxctl -s` to see if your laptop supports the dedicated mode ? 
also it wasn't mentioned in the supergfxctl , so i guess it is not supported yet

**Comment by chikobara** [comment]
i guess dedicated mode is not support any more by Supergfxctl

**Comment by matt22207** [comment]
@chikobara , isn't Dedicated mode "AsusMuxDgpu"?  Here's what my GPU supports:

$ supergfxctl -v
5.2.1

$ supergfxctl -s
[Integrated, Hybrid, AsusMuxDgpu]

Running Wayland on Fedora 40. 
CPU: AMD Ryzen 9 6900HS with Radeon Graphics / AMD ATI Radeon 680M 
Dedicated GPU: AMD ATI Radeon RX 6800S . 
Laptop: ROG Zephyrus G14 GA402RK (with Mux)

**Comment by chikobara** [comment]
> Odd that after switching to AsusMuxDgpu mode, "supergfxctl -s" only shows that single option now. However, I can still switch back using "supergfxctl -m Hybrid" even though that mode doesn't show up in the supported list.

Yep AsusMuxDgpu is the DGPU mode, but you can't actually change to dgpu directly you need to switch to Hybrid first then switch to igpu or dgpu or anything else

can you confirm that the extension now shows these mods if you device supports it, and can you confirm that it blocks the direct switching from dgpu to igpu unless hybrid is between

thank you

**Comment by matt22207** [comment]
- When in Hyrid mode, the extension shows [Integrated, Hybrid, AsusMuxDgpu] available, and allows switching to any other mode.

- When in Integrated mode, the extension shows [Integrated, Hybrid, AsusMuxDgpu] available, and allows switching to any other mode.
 
- When in AsusMuxDgpu mode, the extension shows only [AsusMuxDgpu] and does not allow switching to any other mode. In AsusMuxDgpu mode, `supergfxctl` at the command line also only shows [AsusMuxDgpu], but will execute a switch properly to Hybrid or Integrated.

**Comment by chikobara** [comment]
Thank you for confirming, 
so, I guess it worked fine !
