### ISSUE TITLE
Asking for a tray indicator when dedicated gpu is active or suspended

### ISSUE THREAD

**Issue by mooncoffee1** [chikobara/GPU-Switcher-Supergfxctl#3]
in the old supergfxctl extension, that its no longer mentained for gnome 46, on the tray was a gpu icon, and whe it was nvidia active it was bold, and when suspended it was not bold (u get me). Could you add that too for this extension?

**Comment by chikobara** [comment]
yep yesterday i was thinking about it thx for reminding me

**Comment by mooncoffee1** [comment]
> yep yesterday i was thinking about it thx for reminding me

nice, please come back here, to mention its done, once u get it made please.

**Comment by chikobara** [comment]
@mooncoffee1 its implemented now, can u confirm its working
i'll update it to gnome extension store ASAP
